apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
     app: python
     role: vote
     version: v1
spec:
  containers:
  - name: voting-app
    image: schoolofdevops/vote:v1
    ports:
         - containerPort: 80



